import { useState } from 'react';
import { House, CalendarCheck, DollarSign, Plus, Pencil, Trash2, ShieldCheck, ArrowRight, LoaderCircle } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { useHabitat } from './context';
import { propertyTypes, money, type Property } from '@/lib/habitat-types';
import { api, isDemo } from '@/services/api';
import fallbackImage from '@/assets/mindo.jpg';
const emptyProperty = (): Property => ({ id: '', name: '', type: 'Eco-Lodge', city: '', province: '', region: 'Sierra', cityId: 1, address: '', price: 50, adults: 2, rooms: 1, rating: 0, reviews: 0, image: fallbackImage, active: true, description: '' });
export function AdminPage() {
 const { properties, setProperties, reservations, session, setAuthModal, loading, error: loadError, reload } = useHabitat(); const [editor, setEditor] = useState<Property | null>(null); const [deleting, setDeleting] = useState<Property | null>(null); const [query, setQuery] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [message, setMessage] = useState('');
 if (!session || session.role !== 'PROPIETARIO') return <main className="container admin-gate"><ShieldCheck size={42} /><span className="eyebrow">EL OTRO LADO DE LA HOSPITALIDAD</span><h1 className="editorial">Tu espacio, nuevas historias</h1><p>Accede como anfitrión para gestionar tus alojamientos y acompañar cada reserva.</p><Button size="lg" onClick={() => setAuthModal('login')}>Acceder como anfitrión <ArrowRight /></Button>{isDemo && <p className="demo-notice">Selecciona Anfitrión en el acceso de demostración.</p>}</main>;
 function change<K extends keyof Property>(key: K, value: Property[K]) { setEditor(old => old ? { ...old, [key]: value } : null); }
 async function save(e: React.FormEvent) { e.preventDefault(); if (!editor) return; setError(''); setBusy(true); try { const property = { ...editor, id: editor.id || `H${crypto.randomUUID().slice(0, 8)}` }; const saved = isDemo ? property : editor.id ? await api.updateProperty(property) : await api.createProperty(property); setProperties(old => editor.id ? old.map(p => p.id === editor.id ? saved : p) : [...old, saved]); setMessage(editor.id ? 'Alojamiento actualizado.' : 'Nuevo alojamiento creado.'); setEditor(null); } catch (e) { setError(e instanceof Error ? e.message : 'No pudimos guardar el alojamiento.'); } finally { setBusy(false); } }
 async function remove() { if (!deleting) return; setError(''); setBusy(true); try { if (!isDemo) await api.deleteProperty(deleting.id); setProperties(old => old.filter(p => p.id !== deleting.id)); setMessage('Alojamiento eliminado.'); setDeleting(null); } catch (e) { setError(e instanceof Error ? e.message : 'No pudimos eliminar el alojamiento.'); } finally { setBusy(false); } }
 const filtered = properties.filter(p => `${p.name} ${p.city} ${p.id}`.toLowerCase().includes(query.toLowerCase()));
 return <main className="container admin-page"><div className="admin-heading"><div><span className="eyebrow">PANEL ANFITRIÓN</span><h1 className="editorial">Bienvenido, {session.name}</h1><p>Cuida tus espacios. Haz que cada llegada sea especial.</p></div><Button onClick={() => { setError(''); setEditor(emptyProperty()); }}><Plus /> Nuevo Alojamiento</Button></div>{isDemo && <p className="demo-notice"><ShieldCheck size={16} /> Panel de demostración · los cambios solo se conservan durante esta sesión.</p>}<div className="metrics-grid"><div className="metric"><span><House /> Total Alojamientos</span><strong>{properties.length}</strong><small>{properties.filter(p => p.active).length} activos</small></div><div className="metric"><span><CalendarCheck /> Reservas Activas</span><strong>{reservations.length}</strong><small>{isDemo ? 'Reservas simuladas de esta sesión' : 'Reservas de esta sesión'}</small></div><div className="metric"><span><DollarSign /> Ingresos generados</span><strong>{money(reservations.reduce((sum, r) => sum + r.total, 0))}</strong><small>{isDemo ? 'Importe simulado · sin cobros reales' : 'Importe de reservas de esta sesión'}</small></div></div>{message && <p className="admin-message" role="status">{message}</p>}<div className="admin-toolbar"><h2 className="editorial">Tus alojamientos</h2><input aria-label="Buscar alojamiento" value={query} onChange={e => setQuery(e.target.value)} placeholder="Buscar por nombre, ciudad o ID…" /></div>{loadError ? <div className="empty-state"><p role="alert">{loadError}</p><Button onClick={() => void reload()}>Reintentar</Button></div> : loading ? <div className="loading-inline"><LoaderCircle className="animate-spin" /> Cargando alojamientos…</div> : <div className="table-wrap"><table><thead><tr><th>ID</th><th>Alojamiento</th><th>Tipo</th><th>Ciudad</th><th>Precio / noche</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{filtered.map(p => <tr key={p.id}><td>{p.id}</td><td><div className="table-property"><img src={p.image} width={50} height={42} alt="" /><div><b>{p.name}</b><small>{p.adults} adultos · {p.rooms} habitaciones</small></div></div></td><td>{p.type}</td><td>{p.city}</td><td>{money(p.price)}</td><td><span className={p.active ? 'status active' : 'status'}>● {p.active ? 'Activo' : 'Inactivo'}</span></td><td><div className="table-actions"><Button variant="ghost" size="icon" title="Editar alojamiento" aria-label={`Editar ${p.name}`} onClick={() => { setError(''); setEditor({ ...p }); }}><Pencil /></Button><Button variant="ghost" size="icon" className="danger-icon" title="Eliminar alojamiento" aria-label={`Eliminar ${p.name}`} onClick={() => { setError(''); setDeleting(p); }}><Trash2 /></Button></div></td></tr>)}{filtered.length === 0 && <tr><td colSpan={7}>No hay alojamientos que coincidan con tu búsqueda.</td></tr>}</tbody></table></div>}
 <Dialog open={editor !== null} onOpenChange={open => { if (!open && !busy) setEditor(null); }}><DialogContent className="habitat-modal"><DialogTitle className="editorial modal-heading">{editor?.id ? 'Editar alojamiento' : 'Un nuevo lugar para descubrir'}</DialogTitle><DialogDescription>Comparte los detalles de tu espacio con futuros viajeros.</DialogDescription>{editor && <form onSubmit={save} className="form-stack"><label>Nombre<input required value={editor.name} onChange={e => change('name', e.target.value)} /></label><div className="form-row"><label>Tipo<select value={editor.type} onChange={e => change('type', e.target.value as Property['type'])}>{propertyTypes.filter(t => t !== 'Todos').map(t => <option key={t}>{t}</option>)}</select></label><label>Región<select value={editor.region} onChange={e => change('region', e.target.value)}>{['Sierra', 'Costa', 'Galápagos', 'Amazonía'].map(r => <option key={r}>{r}</option>)}</select></label></div><div className="form-row"><label>Ciudad<input required value={editor.city} onChange={e => change('city', e.target.value)} /></label><label>Ciudad ID<input type="number" min={1} required value={editor.cityId} onChange={e => change('cityId', Number(e.target.value))} /></label></div><label>Provincia<input required value={editor.province} onChange={e => change('province', e.target.value)} /></label><label>Dirección<input required value={editor.address} onChange={e => change('address', e.target.value)} /></label><label>Precio por noche (USD)<input type="number" min={20} max={300} step="0.01" required value={editor.price} onChange={e => change('price', Number(e.target.value))} /></label><div className="form-row"><label>Capacidad de adultos<input required type="number" min={1} max={50} value={editor.adults} onChange={e => change('adults', Number(e.target.value))} /></label><label>Habitaciones<input required type="number" min={1} max={30} value={editor.rooms} onChange={e => change('rooms', Number(e.target.value))} /></label></div><label className="checkbox-label"><input type="checkbox" checked={editor.active} onChange={e => change('active', e.target.checked)} /> Alojamiento activo</label>{error && <p role="alert" className="error-message">{error}</p>}<Button type="submit" disabled={busy}>{busy ? <LoaderCircle className="animate-spin" /> : <House />} Guardar alojamiento</Button></form>}</DialogContent></Dialog>
 <Dialog open={deleting !== null} onOpenChange={open => { if (!open && !busy) setDeleting(null); }}><DialogContent><DialogTitle className="editorial modal-heading">¿Eliminar este alojamiento?</DialogTitle><DialogDescription>Se eliminará {deleting?.name} del catálogo. Esta acción no se puede deshacer.</DialogDescription>{error && <p role="alert" className="error-message">{error}</p>}<div className="form-row"><Button variant="outline" disabled={busy} onClick={() => setDeleting(null)}>Cancelar</Button><Button variant="destructive" disabled={busy} onClick={() => void remove()}><Trash2 /> {busy ? 'Eliminando…' : 'Eliminar alojamiento'}</Button></div></DialogContent></Dialog></main>;
}
