import { useState } from 'react';
import { Compass, ArrowRight, LoaderCircle, UserRound, House, ShieldCheck } from 'lucide-react';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { useHabitat } from './context';
import { api, isDemo } from '@/services/api';
import type { Session } from '@/lib/habitat-types';
export function AuthModal() {
 const { authModal, setAuthModal, setSession } = useHabitat();
 const [role, setRole] = useState<Session['role']>('CLIENTE'); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
 async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setError(''); const form = new FormData(event.currentTarget); const email = String(form.get('email')); const password = String(form.get('password')); const name = String(form.get('name') || email.split('@')[0]); if (password.length < 8) { setError('La contraseña debe tener al menos 8 caracteres.'); return; } setBusy(true); try { if (isDemo) { setSession({ name, email, role }); } else { const response = await api.auth(authModal || 'login', { name, email, password, role }); const token = response.token || response.access_token; if (!token || !response.user) throw new Error('Respuesta de acceso no válida.'); setSession({ ...response.user, token }); } setAuthModal(null); } catch (e) { setError(e instanceof Error ? e.message : 'No pudimos iniciar sesión.'); } finally { setBusy(false); } }
 return <Dialog open={authModal !== null} onOpenChange={open => { if (!open) { setAuthModal(null); setError(''); } }}><DialogContent className="habitat-modal"><div className="modal-brand"><Compass size={32} /></div><DialogTitle className="editorial modal-heading">{authModal === 'register' ? 'Tu próxima historia empieza aquí' : 'Qué bueno tenerte de vuelta'}</DialogTitle><DialogDescription>Conecta con lugares únicos y personas que cuidan Ecuador.</DialogDescription><div className="segmented"><Button variant={authModal === 'login' ? 'default' : 'ghost'} onClick={() => { setAuthModal('login'); setError(''); }}>Iniciar Sesión</Button><Button variant={authModal === 'register' ? 'default' : 'ghost'} onClick={() => { setAuthModal('register'); setError(''); }}>Registrarse</Button></div>
 {isDemo && <p className="demo-notice"><ShieldCheck size={16} /> Acceso de demostración; no se crea una cuenta real.</p>}
 <form onSubmit={submit} className="form-stack">{(authModal === 'register' || isDemo) && <><div className="role-options"><Button type="button" variant={role === 'CLIENTE' ? 'outline' : 'ghost'} className={role === 'CLIENTE' ? 'selected-role' : ''} onClick={() => setRole('CLIENTE')}><UserRound /> Viajero</Button><Button type="button" variant={role === 'PROPIETARIO' ? 'outline' : 'ghost'} className={role === 'PROPIETARIO' ? 'selected-role' : ''} onClick={() => setRole('PROPIETARIO')}><House /> Anfitrión</Button></div><label>Nombre<input name="name" required autoComplete="name" placeholder="Tu nombre" /></label></>}
 <label>Correo electrónico<input name="email" type="email" required autoComplete="email" placeholder="tu@correo.com" /></label><label>Contraseña<input name="password" type="password" minLength={8} required autoComplete={authModal === 'register' ? 'new-password' : 'current-password'} placeholder="Mínimo 8 caracteres" /></label>{error && <p role="alert" className="error-message">{error}</p>}<Button type="submit" size="lg" disabled={busy}>{busy ? <LoaderCircle className="animate-spin" /> : <ArrowRight />}{authModal === 'register' ? 'Crear mi cuenta' : 'Entrar a Hábitat EC'}</Button></form></DialogContent></Dialog>;
}
