import { useEffect, useRef, useState } from 'react';
import { ArrowRight, ArrowLeft, CalendarDays, UsersRound, ShieldCheck, CreditCard, Landmark, CircleCheck, LoaderCircle } from 'lucide-react';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { useHabitat } from './context';
import { demoQuote, money, type Customer, type Property, type Quote } from '@/lib/habitat-types';
import { api, isDemo } from '@/services/api';
export function BookingModal({ property, onClose }: { property: Property | null; onClose: () => void }) {
 const { search, addReservation } = useHabitat(); const [step, setStep] = useState(1); const [quote, setQuote] = useState<Quote | null>(null); const [customer, setCustomer] = useState<Customer>({ firstName: '', lastName: '', email: '' }); const [payment, setPayment] = useState('card'); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [pnr, setPnr] = useState(''); const key = useRef(''); const submitting = useRef(false);
 useEffect(() => { if (!property) return; setStep(1); setError(''); setPnr(''); setQuote(null); key.current = crypto.randomUUID(); setBusy(true); let canceled = false; (isDemo ? Promise.resolve(demoQuote(property, search)) : api.preview(property, search)).then(q => { if (!canceled) setQuote(q); }).catch(e => { if (!canceled) setError(e.message); }).finally(() => { if (!canceled) setBusy(false); }); return () => { canceled = true; }; }, [property, search]);
 async function confirm(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); if (!property || !quote || submitting.current) return; submitting.current = true; setBusy(true); setError(''); try { const response = isDemo ? { pnr: `HAB-EC-${crypto.randomUUID().slice(0, 8).toUpperCase()}` } : await api.createOrder(property, search, customer, payment, key.current, quote.quoteId); setPnr(response.pnr); addReservation({ pnr: response.pnr, propertyId: property.id, total: quote.total, checkin: search.checkin, checkout: search.checkout }); setStep(3); } catch (e) { setError(e instanceof Error ? e.message : 'No pudimos confirmar la reserva.'); } finally { setBusy(false); submitting.current = false; } }
 return <Dialog open={property !== null} onOpenChange={open => { if (!open && !busy) onClose(); }}><DialogContent className="habitat-modal booking-modal"><DialogTitle className="editorial modal-heading">{step === 3 ? 'Tu escapada está confirmada' : step === 1 ? 'Un lugar para tu próxima historia' : 'Confirma tu reserva'}</DialogTitle><DialogDescription>{step === 3 ? 'Guarda tu código de reserva.' : `Paso ${step} de 2 · ${step === 1 ? 'Tu estancia y tus datos' : 'Método de pago'}`}</DialogDescription>{isDemo && <p className="demo-notice"><ShieldCheck size={16} /> Reserva simulada · no se realizará ningún cobro.</p>}
 {step === 3 ? <div className="success-state"><CircleCheck size={54} /><h3 className="editorial">¡Nos vemos en Ecuador!</h3><p>{property?.name}</p><strong className="pnr">{pnr}</strong><p>{search.checkin} → {search.checkout}</p><Button onClick={onClose}>Volver al catálogo <ArrowRight /></Button></div> : <>{property && <div className="booking-property"><img src={property.image} alt={property.name} width={96} height={80} /><div><h3 className="editorial">{property.name}</h3><p>{property.city}, {property.province}</p><span><CalendarDays size={14} /> {search.checkin} → {search.checkout}</span><span><UsersRound size={14} /> {search.adults} adultos · {search.rooms} habitación(es)</span></div></div>}{busy && !quote && <div className="loading-inline"><LoaderCircle className="animate-spin" /> Preparando tu cotización…</div>}{quote && <div className="quote-lines"><span>{money(property?.price || 0)} × {quote.nights} noches <b>{money(quote.base)}</b></span><span>Tarifa de servicio {isDemo ? '(8%, demo)' : ''}<b>{money(quote.service)}</b></span><span>Impuestos {isDemo ? '(15%, demo)' : ''}<b>{money(quote.tax)}</b></span><span className="quote-total">Total USD <b>{money(quote.total)}</b></span></div>}
 {step === 1 ? <form className="form-stack" onSubmit={e => { e.preventDefault(); setStep(2); }}><div className="form-row"><label>Nombre<input required value={customer.firstName} onChange={e => setCustomer(c => ({ ...c, firstName: e.target.value }))} autoComplete="given-name" /></label><label>Apellido<input required value={customer.lastName} onChange={e => setCustomer(c => ({ ...c, lastName: e.target.value }))} autoComplete="family-name" /></label></div><label>Correo electrónico<input type="email" required value={customer.email} onChange={e => setCustomer(c => ({ ...c, email: e.target.value }))} autoComplete="email" /></label><Button size="lg" disabled={!quote || busy}>Continuar al pago <ArrowRight /></Button></form> : <form className="form-stack" onSubmit={confirm}><div className="role-options"><Button type="button" variant={payment === 'card' ? 'outline' : 'ghost'} className={payment === 'card' ? 'selected-role' : ''} onClick={() => setPayment('card')}><CreditCard /> Tarjeta</Button><Button type="button" variant={payment === 'transfer' ? 'outline' : 'ghost'} className={payment === 'transfer' ? 'selected-role' : ''} onClick={() => setPayment('transfer')}><Landmark /> Billetera / Transferencia</Button></div>{payment === 'card' ? <>{isDemo && <p className="text-xs text-muted-foreground">Usa únicamente datos ficticios. Nunca ingreses una tarjeta real.</p>}<label>Número de tarjeta<input inputMode="numeric" pattern="[0-9 ]{13,23}" maxLength={23} required placeholder="4242 4242 4242 4242" /></label><label>Titular<input required placeholder="Nombre como aparece en la tarjeta" /></label><div className="form-row"><label>Vencimiento<input required pattern="(0[1-9]|1[0-2])/[0-9]{2}" placeholder="MM/AA" maxLength={5} /></label><label>CVC<input required type="password" inputMode="numeric" pattern="[0-9]{3,4}" maxLength={4} placeholder="•••" /></label></div></> : <div className="transfer-notice"><Landmark size={30} /><strong>Deuna / Banco Pichincha</strong><p>{isDemo ? 'Confirmación de transferencia simulada. No se requiere enviar dinero.' : 'La confirmación enviará tu solicitud de pago al alojamiento. No transfieras sin instrucciones oficiales.'}</p></div>}<p className="payment-security"><ShieldCheck size={16} /> Solicitud protegida por Idempotency-Key</p><div className="form-row"><Button type="button" variant="ghost" onClick={() => setStep(1)} disabled={busy}><ArrowLeft /> Atrás</Button><Button type="submit" disabled={busy || !quote}>{busy ? <LoaderCircle className="animate-spin" /> : <ShieldCheck />} {isDemo ? 'Confirmar reserva demo' : 'Pagar y Confirmar Reserva'}</Button></div></form>}{error && <p role="alert" className="error-message">{error}</p>}</>}</DialogContent></Dialog>;
}
