import { useMemo, useState } from 'react';
import { es } from 'date-fns/locale';
import { format } from 'date-fns';
import { MapPin, Search, CalendarDays, UsersRound, Minus, Plus, ChevronDown, ArrowUpRight, Leaf, Mountain, Waves, TreePine, Compass, Heart, Star, SlidersHorizontal, ArrowRight, ShieldCheck, Sparkles } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover';
import { Calendar } from '@/components/ui/calendar';
import { destinations } from '@/lib/habitat-data';
import { propertyTypes, defaultSearch, type Property } from '@/lib/habitat-types';
import { useHabitat } from './context';
import { BookingModal } from './booking-modal';
import { api, isDemo } from '@/services/api';
import hero from '@/assets/ecuador-hero.jpg';
export function Marketplace() {
 const { properties, loading, error: loadError, search, setSearch, reload } = useHabitat(); const [type, setType] = useState('Todos'); const [region, setRegion] = useState('Todo Ecuador'); const [maxPrice, setMaxPrice] = useState(300); const [favorites, setFavorites] = useState<string[]>([]); const [selected, setSelected] = useState<Property | null>(null); const [results, setResults] = useState<Property[] | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [destinationOpen, setDestinationOpen] = useState(false); const [datesOpen, setDatesOpen] = useState(false); const [sort, setSort] = useState('recommended');
 const filtered = useMemo(() => { const list = (results || properties).filter(p => p.active && (type === 'Todos' || p.type === type) && (region === 'Todo Ecuador' || p.region === region) && p.price <= maxPrice && (!search.destination || `${p.city}, ${p.province}`.toLowerCase().includes(search.destination.toLowerCase())) && p.adults >= search.adults && p.rooms >= search.rooms); if (sort === 'price') return list.sort((a, b) => a.price - b.price); if (sort === 'rating') return list.sort((a, b) => b.rating - a.rating); return list; }, [properties, results, type, region, maxPrice, search, sort]);
 async function submit(e: React.FormEvent) { e.preventDefault(); setError(''); if (!search.checkin || !search.checkout || search.checkout <= search.checkin) { setError('Selecciona una salida posterior a la llegada.'); return; } setBusy(true); try { setResults(await api.search(search)); document.getElementById('stays')?.scrollIntoView({ behavior: 'smooth', block: 'start' }); } catch (e) { setError(e instanceof Error ? e.message : 'La búsqueda no está disponible.'); } finally { setBusy(false); } }
 function reset() { setSearch(defaultSearch()); setType('Todos'); setRegion('Todo Ecuador'); setMaxPrice(300); setResults(null); }
 const dateText = (date: string) => date ? format(new Date(`${date}T12:00:00`), 'd MMM', { locale: es }) : 'Añadir fechas';
 return <main><section className="hero"><img src={hero} alt="Cabaña sostenible frente al volcán Cotopaxi en los Andes ecuatorianos" width={1920} height={1024} fetchPriority="high" className="hero-image" /><div className="hero-shade" /><div className="container hero-content"><span className="hero-eyebrow"><span /> PEQUEÑO PAÍS. INFINITAS HISTORIAS.</span><h1 className="editorial">Hospedajes conscientes<br />en los rincones más<br /><em>mágicos del Ecuador.</em></h1><p>Lugares que te conectan con la naturaleza.<br />Estancias que dejan huella en ti, no en el planeta.</p><div className="hero-detail"><Leaf size={17} /><span>Selección local. Experiencias auténticas.</span></div></div><span className="hero-location"><MapPin size={14} /> Cotopaxi, Sierra ecuatoriana</span></section>
 <div className="container search-wrap"><form className="search-bar" onSubmit={submit}><Popover open={destinationOpen} onOpenChange={setDestinationOpen}><PopoverTrigger asChild><Button variant="ghost" className="search-field"><MapPin /><span><b>¿A dónde vamos?</b><span>{search.destination || 'Explora un destino'}</span></span><ChevronDown /></Button></PopoverTrigger><PopoverContent className="destination-search"><label>Tu destino<input autoFocus value={search.destination} placeholder="Ciudad o provincia" onChange={e => { setSearch(s => ({ ...s, destination: e.target.value })); setResults(null); }} /></label><div>{destinations.filter(d => d.toLowerCase().includes(search.destination.toLowerCase())).map(d => <Button variant="ghost" key={d} onClick={() => { setSearch(s => ({ ...s, destination: d })); setResults(null); setDestinationOpen(false); }}><MapPin />{d}</Button>)}</div><Button variant="link" onClick={() => { setSearch(s => ({ ...s, destination: '' })); setDestinationOpen(false); }}>Todo Ecuador</Button></PopoverContent></Popover>
 <Popover open={datesOpen} onOpenChange={setDatesOpen}><PopoverTrigger asChild><Button variant="ghost" className="search-field"><CalendarDays /><span><b>Llegada — Salida</b><span>{dateText(search.checkin)} — {dateText(search.checkout)}</span></span></Button></PopoverTrigger><PopoverContent className="date-popover" align="center"><Calendar mode="range" locale={es} selected={{ from: new Date(`${search.checkin}T12:00:00`), to: search.checkout ? new Date(`${search.checkout}T12:00:00`) : undefined }} disabled={{ before: new Date(new Date().setHours(0, 0, 0, 0)) }} onSelect={range => { if (range?.from) setSearch(s => ({ ...s, checkin: format(range.from as Date, 'yyyy-MM-dd'), checkout: range.to ? format(range.to, 'yyyy-MM-dd') : '' })); }} /><div className="form-row"><label>Llegada<input type="date" aria-label="Fecha de llegada" min={new Date().toISOString().slice(0, 10)} value={search.checkin} onChange={e => setSearch(s => ({ ...s, checkin: e.target.value }))} /></label><label>Salida<input type="date" aria-label="Fecha de salida" min={search.checkin} value={search.checkout} onChange={e => setSearch(s => ({ ...s, checkout: e.target.value }))} /></label></div><Button className="w-full mt-3" onClick={() => setDatesOpen(false)}>Guardar fechas</Button></PopoverContent></Popover>
 <Popover><PopoverTrigger asChild><Button variant="ghost" className="search-field"><UsersRound /><span><b>Tu compañía</b><span>{search.adults} adultos · {search.rooms} habitación{search.rooms > 1 ? 'es' : ''}</span></span><ChevronDown /></Button></PopoverTrigger><PopoverContent>{(['adults', 'rooms'] as const).map(key => <div className="guest-row" key={key}><span>{key === 'adults' ? 'Adultos' : 'Habitaciones'}</span><div><Button variant="outline" size="icon" aria-label={`Reducir ${key === 'adults' ? 'adultos' : 'habitaciones'}`} disabled={search[key] <= 1} onClick={() => setSearch(s => ({ ...s, [key]: Math.max(1, s[key] - 1) }))}><Minus /></Button><b>{search[key]}</b><Button variant="outline" size="icon" aria-label={`Añadir ${key === 'adults' ? 'adultos' : 'habitaciones'}`} disabled={search[key] >= 12} onClick={() => setSearch(s => ({ ...s, [key]: s[key] + 1 }))}><Plus /></Button></div></div>)}</PopoverContent></Popover><Button type="submit" size="lg" className="search-submit" disabled={busy}><Search />{busy ? 'Buscando…' : 'Buscar estancia'}</Button></form>{error && <p className="error-message" role="alert">{error}</p>}</div>
 <section className="container catalog-section" id="stays"><div className="region-tabs">{[{ name: 'Todo Ecuador', icon: Compass }, { name: 'Sierra', icon: Mountain }, { name: 'Costa', icon: Waves }, { name: 'Galápagos', icon: Sparkles }, { name: 'Amazonía', icon: TreePine }].map(({ name, icon: Icon }) => <Button key={name} variant="ghost" className={region === name ? 'region-tab active' : 'region-tab'} onClick={() => { setRegion(name); setResults(null); }}><Icon size={19} />{name}</Button>)}<span className="region-note"><Leaf size={15} /> Viaja cerca. Conecta más.</span></div><div className="catalog-heading"><div><span className="eyebrow">ESCAPADAS CON PROPÓSITO</span><h2 className="editorial">Tu próximo lugar favorito</h2><p>Alojamientos extraordinarios, elegidos con cuidado.</p></div><label className="sort-label">Ordenar por <select aria-label="Ordenar alojamientos" value={sort} onChange={e => setSort(e.target.value)}><option value="recommended">Recomendados</option><option value="price">Menor precio</option><option value="rating">Mejor puntuación</option></select></label></div>
 <div className="filter-bar"><div className="type-filters">{propertyTypes.map(t => <Button key={t} variant={type === t ? 'default' : 'outline'} className="filter-chip" onClick={() => setType(t)}>{t}</Button>)}</div><Popover><PopoverTrigger asChild><Button variant="outline" className="price-filter"><SlidersHorizontal /> Precio {maxPrice < 300 ? `≤ $${maxPrice}` : ''}</Button></PopoverTrigger><PopoverContent><label>Hasta ${maxPrice} USD por noche<input aria-label="Precio máximo" type="range" min={20} max={300} step={5} value={maxPrice} onChange={e => setMaxPrice(Number(e.target.value))} /></label><div className="range-labels"><span>$20</span><span>$300</span></div></PopoverContent></Popover></div><div className="results-caption"><span>{loading || busy ? 'Encontrando tu próxima escapada…' : `${filtered.length} alojamientos para desconectar`}</span></div>
 {loadError ? <div className="empty-state"><p role="alert">{loadError}</p><Button onClick={() => void reload()}>Reintentar</Button></div> : loading || busy ? <div className="property-grid">{[1, 2, 3].map(n => <div className="property-skeleton" key={n}><div /><span /><span /></div>)}</div> : filtered.length === 0 ? <div className="empty-state"><Compass size={40} /><h3 className="editorial">Hay más caminos por descubrir</h3><p>No encontramos estancias con estos filtros. Prueba otro destino o amplía tu presupuesto.</p><Button variant="outline" onClick={reset}>Restablecer filtros</Button></div> : <div className="property-grid">{filtered.map(p => <article className="property-card" key={p.id}><div className="property-image"><img src={p.image} width={640} height={450} loading="lazy" alt={p.name} /><span className="property-badge"><Leaf size={12} /> {p.type}</span><Button variant="image" size="icon" aria-label={favorites.includes(p.id) ? `Quitar ${p.name} de favoritos` : `Guardar ${p.name}`} className={favorites.includes(p.id) ? 'favorite saved' : 'favorite'} onClick={() => setFavorites(old => old.includes(p.id) ? old.filter(id => id !== p.id) : [...old, p.id])}><Heart /></Button></div><div className="property-info"><div className="property-location"><MapPin size={13} /> {p.city}, {p.province}</div><h3 className="editorial">{p.name}</h3><div className="property-review"><span><Star size={12} fill="currentColor" /> {p.rating.toFixed(1)}</span><b>Excelente</b><span className="review-count">({p.reviews} reseñas)</span></div><div className="property-bottom"><div><span className="property-price">${p.price}</span><span className="per-night"> / noche</span><small>Precio en USD</small></div><Button variant="reserve" onClick={() => { if (search.checkout <= search.checkin) { setError('Elige fechas válidas antes de reservar.'); return; } setSelected(p); }}>Ver y Reservar <ArrowUpRight /></Button></div></div></article>)}</div>}
 <div className="catalog-bottom"><Leaf size={17} /><p>Cada estancia es una forma de cuidar lo que nos hace únicos.</p><span>ECUADOR, A TU RITMO.</span></div></section><section className="trust-band"><div className="container trust-grid"><div><Leaf /><span><b>Más cerca de la naturaleza</b><small>Espacios que respetan su entorno.</small></span></div><div><ShieldCheck /><span><b>Hospitalidad con confianza</b><small>Información clara, sin sorpresas.</small></span></div><div><Heart /><span><b>Historias, no solo estancias</b><small>Viajes que se quedan contigo.</small></span></div></div></section><BookingModal property={selected} onClose={() => setSelected(null)} /></main>;
}
