import { Link } from '@tanstack/react-router';
import { useState } from 'react';
import { Compass, ChevronDown, ArrowUpRight, Instagram, Globe, Leaf, Menu, LogOut, UserRound } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { useHabitat } from './context';
import { AuthModal } from './auth-modal';
export function SiteHeader() {
 const { session, setSession, setAuthModal, setSearch } = useHabitat(); const [mobile, setMobile] = useState(false);
 return <header className="site-header"><div className="container header-inner"><Link to="/" className="brand"><span className="brand-icon"><Compass /></span><span>Hábitat <span className="brand-ec">EC</span></span></Link><nav className={mobile ? 'main-nav mobile-open' : 'main-nav'}><Link to="/" activeProps={{ className: 'nav-active' }} onClick={() => setMobile(false)}>Explorar Alojamientos</Link><Popover><PopoverTrigger asChild><Button variant="ghost" className="nav-destinations">Destinos del Ecuador <ChevronDown size={14} /></Button></PopoverTrigger><PopoverContent className="destination-nav">{['Pichincha', 'Tungurahua', 'Galápagos', 'Napo'].map(destination => <Button asChild variant="ghost" key={destination}><Link to="/" onClick={() => { setSearch(s => ({ ...s, destination })); setMobile(false); }}>{destination}<ArrowUpRight /></Link></Button>)}</PopoverContent></Popover><Link to="/admin" activeProps={{ className: 'nav-active' }} onClick={() => setMobile(false)}>Panel Anfitrión</Link></nav><div className="header-actions">{session ? <Popover><PopoverTrigger asChild><Button variant="ghost" className="account-button"><span className="avatar">{session.name.slice(0, 2).toUpperCase()}</span><span className="account-name">{session.name}<small>{session.role}</small></span><ChevronDown /></Button></PopoverTrigger><PopoverContent><p className="text-sm mb-3">{session.email}</p><Button variant="ghost" onClick={() => setSession(null)}><LogOut /> Cerrar Sesión</Button></PopoverContent></Popover> : <><Button variant="ghost" className="login-button" onClick={() => setAuthModal('login')}>Iniciar Sesión</Button><Button onClick={() => setAuthModal('register')}>Registrarse <ArrowUpRight /></Button></>}<Button variant="ghost" size="icon" className="mobile-menu" aria-label="Abrir navegación" onClick={() => setMobile(!mobile)}><Menu /></Button></div></div></header>;
}
const info: Record<string, string> = {
 'Guía para anfitriones': 'Publica espacios con información clara, fotografías fieles y tarifas transparentes. Mantén la disponibilidad actualizada y ofrece una bienvenida responsable con el entorno.',
 'Términos de servicio': 'Documento provisional de demostración. Las reservas y pagos de esta versión no son reales. Las condiciones definitivas se publicarán antes de habilitar reservas reales.',
 'Políticas de cancelación': 'Las políticas dependen de cada alojamiento y deberán confirmarse antes del pago. Esta versión de demostración no genera cargos ni reservas reales.',
 'Privacidad': 'En esta demostración los datos se usan únicamente durante la sesión. No ingreses datos bancarios reales. La política definitiva se publicará antes del lanzamiento.',
 'Instagram': 'Hábitat EC todavía no ha añadido su cuenta oficial de Instagram.',
};
export function SiteFooter() {
 const { setAuthModal, setSearch } = useHabitat(); const [document, setDocument] = useState<string | null>(null);
 return <><footer className="site-footer"><div className="container footer-grid"><div><Link to="/" className="brand"><Compass /> Hábitat <span className="brand-ec">EC</span></Link><p>Viajar con sentido.<br />Habitar Ecuador de otra manera.</p><div className="footer-social"><Button variant="ghost" size="icon" aria-label="Instagram" onClick={() => setDocument('Instagram')}><Instagram /></Button><Globe size={18} /><span>Hecho en Ecuador</span></div></div><div><h3>Encuentra tu destino</h3>{[['Quito Histórico', 'Quito'], ['Bosque Nublado de Mindo', 'Mindo'], ['Playas de Manabí', 'Manabí'], ['Islas Galápagos', 'Galápagos']].map(([label, destination]) => <Link key={label} to="/" onClick={() => setSearch(s => ({ ...s, destination: destination || '' }))}>{label}</Link>)}</div><div><h3>Para anfitriones</h3><Button variant="link" onClick={() => setAuthModal('register')}>Registra tu cabaña</Button><Button variant="link" onClick={() => setDocument('Guía para anfitriones')}>Guía para anfitriones</Button><Link to="/admin">Panel administrativo</Link></div><div><h3>Viaja con confianza</h3>{['Términos de servicio', 'Políticas de cancelación', 'Privacidad'].map(label => <Button key={label} variant="link" onClick={() => setDocument(label)}>{label}</Button>)}<span className="footer-sustainable"><Leaf size={16} /> Turismo con propósito</span></div></div><div className="container footer-bottom"><span>© 2026 Hábitat EC. Todos los derechos reservados.</span><span><Globe size={14} /> Español (EC) <span>USD ($)</span></span></div></footer><Dialog open={document !== null} onOpenChange={open => { if (!open) setDocument(null); }}><DialogContent><DialogTitle className="editorial">{document}</DialogTitle><DialogDescription>{document ? info[document] : ''}</DialogDescription></DialogContent></Dialog><AuthModal /></>;
}
